// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIMOITO.Data;

namespace PIMOITO.Migrations
{
    [DbContext(typeof(PIMOITOContext))]
    partial class PIMOITOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PIMOITO.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<int>("Cep");

                    b.Property<string>("Cidade");

                    b.Property<string>("Estado");

                    b.Property<string>("Logradouro");

                    b.Property<int>("Numero");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("PIMOITO.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Cpf");

                    b.Property<int?>("EnderecoId");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("PIMOITO.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ddd");

                    b.Property<int>("Numero");

                    b.Property<int?>("PessoaId");

                    b.Property<int?>("TipoId");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TipoId");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("PIMOITO.Models.TipoDeTelefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.ToTable("TipoDeTelefone");
                });

            modelBuilder.Entity("PIMOITO.Models.Pessoa", b =>
                {
                    b.HasOne("PIMOITO.Models.Endereco", "Endereco")
                        .WithMany("Pessoas")
                        .HasForeignKey("EnderecoId");
                });

            modelBuilder.Entity("PIMOITO.Models.Telefone", b =>
                {
                    b.HasOne("PIMOITO.Models.Pessoa")
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaId");

                    b.HasOne("PIMOITO.Models.TipoDeTelefone", "Tipo")
                        .WithMany("Telefones")
                        .HasForeignKey("TipoId");
                });
#pragma warning restore 612, 618
        }
    }
}
